name: blockcolour
version: 1.0
author: libus
main: com.libus.blockcolour.Main
api-version: 1.16
commands:
  blockcolour:
    description: Get and compare block colour
    usage: /blockcolour <similar|different|complement>
    aliases: [bc]